name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache Prisma Client
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.prisma
            apps/api/node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - name: Setup test database directory
        run: mkdir -p apps/api/test/tmp

      - name: Generate Prisma Client
        run: bun run db:generate
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db

      - name: Run database migrations
        run: bun run db:migrate
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db

      - name: Lint code
        id: lint
        continue-on-error: true
        run: bun run lint > lint_errors.log 2>&1

      - name: Triage and Fix Lint Errors
        if: steps.lint.outcome == 'failure'
        id: ai_lint_triage
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          LINT_ERRORS=$(cat lint_errors.log)
          PROMPT_TEMPLATE=$(cat .github/workflows/lint-fix.prompt)
          PROMPT="$PROMPT_TEMPLATE\n\n**Errors**:\n$LINT_ERRORS"
          
          API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=$GEMINI_API_KEY"
          JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{ "contents": [ { "parts": [ { "text": $prompt } ] } ] }')
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$API_URL" | jq -r '.candidates[0].content.parts[0].text')

          if [[ $(echo "$RESPONSE" | head -n 1) == "AUTOMATIC_FIX:" ]]; then
            echo "AI provided an automatic fix."
            FIX_COMMANDS=$(echo "$RESPONSE" | tail -n +2)
            eval "$FIX_COMMANDS"
            echo "fix_type=code" >> $GITHUB_OUTPUT
          elif [[ $(echo "$RESPONSE" | head -n 1) == "MANUAL_SUGGESTION:" ]]; then
            echo "AI provided a manual suggestion."
            COMMENT_BODY=$(echo "$RESPONSE" | tail -n +2)
            echo "fix_type=notification" >> $GITHUB_OUTPUT
            echo "comment_body<<EOF" >> $GITHUB_OUTPUT
            echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "AI returned an unexpected response format."
            exit 1
          fi

      - name: Post Lint Fix Suggestion
        if: steps.ai_lint_triage.outputs.fix_type == 'notification'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ai-lint-suggestion
          message: ${{ steps.ai_lint_triage.outputs.comment_body }}

      - name: Verify and Commit Lint Fix
        if: steps.ai_lint_triage.outputs.fix_type == 'code'
        run: |
          echo "Verifying AI fix by re-running the linter..."
          if ! bun run lint; then
            echo "AI fix did not resolve linting errors. Failing workflow."
            exit 1
          fi
          
          echo "Linting errors fixed successfully. Committing changes..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(ci): apply automatic linting fixes"
          git push

      - name: Type check
        run: bun run type-check

      - name: Run unit tests
        run: bun run test
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: Run E2E tests
        run: bun run test:e2e
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: Build applications
        run: bun run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./apps/api/coverage/lcov.info
          flags: backend
          name: backend-coverage

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run security audit
        run: bun audit

      - name: Run dependency review
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'

  docker:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t talent-radar-api:test -f apps/api/Dockerfile .
