name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache Prisma Client
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.prisma
            apps/api/node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - name: Setup test database directory
        run: mkdir -p apps/api/test/tmp

      - name: Generate Prisma Client
        run: bun run db:generate
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db

      - name: Run database migrations
        run: bun run db:migrate
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db

      - name: Lint code
        id: lint
        continue-on-error: true
        run: bun run lint > lint_errors.log 2>&1

      - name: Auto-fix Lint Errors with AI
        if: failure() && steps.lint.outcome == 'failure'
        id: ai_lint_fix
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          LINT_ERRORS=$(cat lint_errors.log)
          PROMPT="You are an expert programmer tasked with fixing linting errors. Based on the following errors, provide a series of shell commands, primarily using 'sed', to fix the files directly. Output ONLY the shell commands. If you cannot find a fix, output 'No fix found'.\n\nErrors:\n$LINT_ERRORS"
          
          API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=$GEMINI_API_KEY"
          JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{ "contents": [ { "parts": [ { "text": $prompt } ] } ] }')
          FIX_COMMANDS=$(curl -s -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$API_URL" | jq -r '.candidates[0].content.parts[0].text')

          if [[ -z "$FIX_COMMANDS" || "$FIX_COMMANDS" == "null" || "$FIX_COMMANDS" == "No fix found" ]]; then
            echo "AI did not return a valid command. Output was: $FIX_COMMANDS"
            exit 1
          fi

          echo "Applying AI-generated fixes..."
          eval "$FIX_COMMANDS"
          echo "applied_fix=true" >> $GITHUB_OUTPUT

      - name: Verify and Commit Lint Fix
        if: steps.ai_lint_fix.outputs.applied_fix == 'true'
        run: |
          echo "Verifying AI fix by re-running the linter..."
          if ! bun run lint; then
            echo "AI fix did not resolve linting errors. Failing workflow."
            exit 1
          fi
          
          echo "Linting errors fixed successfully. Committing changes..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(ci): apply automatic linting fixes"
          git push

      - name: Type check
        run: bun run type-check

      - name: Run unit tests
        run: bun run test
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: Run E2E tests
        run: bun run test:e2e
        env:
          DATABASE_URL: file:./test/tmp/ci-test.db
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: Build applications
        run: bun run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./apps/api/coverage/lcov.info
          flags: backend
          name: backend-coverage

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run security audit
        id: bun_audit
        continue-on-error: true
        run: bun audit > bun_audit.log 2>&1

      - name: Run dependency review
        id: dep_review
        continue-on-error: true
        run: actions/dependency-review-action@v4 > dep_review.log 2>&1

      - name: Triage and Fix Security Issues
        id: ai_security_triage
        if: steps.bun_audit.outcome == 'failure' || steps.dep_review.outcome == 'failure'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          BUN_AUDIT_LOG="bun_audit.log"
          DEP_REVIEW_LOG="dep_review.log"

          # Triage: Check for the specific configuration error first.
          if grep -q "Dependency review is not supported" "$DEP_REVIEW_LOG"; then
            echo "Detected configuration error. Asking AI for explanation..."
            PROMPT="The 'Dependency Review' GitHub Action failed with the following error. Analyze it and write a user-friendly comment for the pull request explaining the problem and how to fix it in the repository settings. Provide a direct link to the settings page. Start the comment with '### Dependency Review Configuration Error'. Error log: $(cat $DEP_REVIEW_LOG)"
            API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=$GEMINI_API_KEY"
            JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{ "contents": [ { "parts": [ { "text": $prompt } ] } ] }')
            COMMENT_BODY=$(curl -s -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$API_URL" | jq -r '.candidates[0].content.parts[0].text')
            
            echo "fix_type=notification" >> $GITHUB_OUTPUT
            echo "comment_body<<EOF" >> $GITHUB_OUTPUT
            echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

          # If not a config error, proceed with vulnerability fixing.
          else
            echo "Detected vulnerabilities. Asking AI for code fix..."
            PROMPT="You are a cybersecurity expert. The following security checks failed. Analyze all reports and provide a consolidated series of 'bun update <package>' commands to fix all vulnerabilities. Only output the shell commands. If no fix is possible, output 'No fix found'.\n\nBUN AUDIT REPORT:\n$(cat $BUN_AUDIT_LOG)\n\nDEPENDENCY REVIEW REPORT:\n$(cat $DEP_REVIEW_LOG)"
            API_URL="https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key=$GEMINI_API_KEY"
            JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{ "contents": [ { "parts": [ { "text": $prompt } ] } ] }')
            FIX_COMMANDS=$(curl -s -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$API_URL" | jq -r '.candidates[0].content.parts[0].text')

            if [[ -z "$FIX_COMMANDS" || "$FIX_COMMANDS" == "null" || "$FIX_COMMANDS" == "No fix found" ]]; then
              echo "AI did not return a valid command for security issues. Output was: $FIX_COMMANDS"
              exit 1 # Exit without setting output
            fi

            echo "Applying AI-generated security fixes..."
            eval "$FIX_COMMANDS"
            echo "fix_type=code" >> $GITHUB_OUTPUT
          fi

      - name: Post Configuration Notification
        if: steps.ai_security_triage.outputs.fix_type == 'notification'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: dependency-review-config-error
          message: ${{ steps.ai_security_triage.outputs.comment_body }}

      - name: Verify and Commit Code Fix
        if: steps.ai_security_triage.outputs.fix_type == 'code'
        run: |
          echo "Verifying AI fix by re-running security audit..."
          if ! bun audit; then
            echo "AI fix did not resolve bun audit issues. Failing workflow."
            exit 1
          fi
          
          echo "Security issues fixed successfully. Committing changes..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bun.lockb
          git commit -m "chore(ci): apply automatic security audit fixes"
          git push

  docker:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t talent-radar-api:test -f apps/api/Dockerfile .
