name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AI Code Review
        uses: flux-actions/gemini-pr-reviewer@v1
        with:
          gemini-key: ${{ secrets.GEMINI_API_KEY }}
