name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch history for git diff

      - name: Get PR Diff
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: AI Code Review
        uses: google-github-actions/github-ai-code-review@v1
        id: ai_review
        with:
          model: 'gemini-1.5-flash-latest'
          api_key: ${{ secrets.GEMINI_API_KEY }}
          diff: ${{ steps.get_diff.outputs.diff }}
          prompt: |
            You are an AI code reviewer. Focus only on critical and high severity issues.
            
            Instructions:
            1. Report only critical (bugs, security, performance) and high (design/architecture) issues
            2. Provide file and line context
            3. Be concise and actionable
            4. If no issues found, respond: "No critical or high severity issues found."
          max_tokens: 2048

      - name: Post Review Comment
        if: steps.ai_review.outputs.response != 'No critical or high severity issues found.'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ai-review
          message: |
            ### ✨ AI Code Review ✨
            
            ${{ steps.ai_review.outputs.response }}
