name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch history for git diff

      - name: Get PR Diff
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call Gemini API for Review
        id: gemini_review
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            ${{ steps.get_diff.outputs.diff }}
          prompt-file: .github/workflows/pr-review.prompt

      - name: Post Review Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gemini-review
          message: |
            ### ✨ AI Review ✨
            
            ${{ steps.gemini_review.outputs.gemini-response }}
