name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch history for git diff

      - name: Get PR Diff
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call Gemini API for Review
        id: gemini_review
        run: |
          # Write prompt to a temporary file to handle complex content
          cat > prompt.txt << 'EOF'
          You are an AI code reviewer. Your task is to analyze the provided git diff and identify only the most severe issues.

          **Instructions:**
          1.  **Focus only on `critical` and `high` severity suggestions.** Do not report medium or low-severity issues like style conventions or minor nitpicks.
          2.  **You MUST use one of the following severity levels for your findings:**
              *   `critical`: A potential bug, security vulnerability, or major performance issue.
              *   `high`: A major design or architectural issue.
          3.  **Provide context.** For each suggestion, specify the file and line number if possible.
          4.  **Be concise.** Keep your suggestions and reasoning brief and to the point.
          5.  **If you find no critical or high issues, you MUST respond with the single phrase `No critical or high severity issues found.`**

          ${{ steps.get_diff.outputs.diff }}
          EOF
          
          # Install and run Gemini CLI directly
          echo "🚀 Installing Gemini CLI..."
          npm install -g @google/gemini-cli@latest
          
          # Run Gemini and capture output with error handling
          echo "🔍 Running Gemini analysis..."
          if gemini-cli --api-key="${{ secrets.GEMINI_API_KEY }}" --prompt="$(cat prompt.txt)" > gemini_response.txt 2>&1; then
            echo "✅ Gemini CLI completed successfully"
          else
            echo "❌ Gemini CLI failed with exit code $?"
            echo "Error output:"
            cat gemini_response.txt
          fi
          
          # Debug: Show raw response file content
          echo "📄 Raw response file size: $(wc -c < gemini_response.txt) bytes"
          echo "📄 Raw response content:"
          cat gemini_response.txt
          echo "📄 End of raw response"
          
          # Read the response and set output
          GEMINI_RESPONSE=$(cat gemini_response.txt)
          echo "📝 Setting output variable with ${#GEMINI_RESPONSE} characters"
          
          echo "gemini-response<<EOF" >> $GITHUB_OUTPUT
          echo "$GEMINI_RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Clean up
          rm -f prompt.txt gemini_response.txt

      - name: Debug Gemini Response
        id: debug_response
        env:
          RESPONSE: ${{ steps.gemini_review.outputs.gemini-response }}
        run: |
          echo "🔍 Debugging Gemini Response Output"
          echo "=================================="
          echo "Response length: ${#RESPONSE} characters"
          echo "Response preview (first 200 chars):"
          echo "${RESPONSE:0:200}"
          if [[ ${#RESPONSE} -gt 200 ]]; then
            echo "... (truncated, total ${#RESPONSE} characters)"
          fi
          echo "=================================="
          
          # Check if response is empty or contains only whitespace
          if [[ -z "${RESPONSE// }" ]]; then
            echo "⚠️  WARNING: Gemini response is empty!"
            echo "response_status=empty" >> $GITHUB_OUTPUT
          else
            echo "✅ Gemini response contains content (${#RESPONSE} characters)"
            echo "response_status=valid" >> $GITHUB_OUTPUT
          fi

      - name: Post Review Comment
        if: steps.gemini_review.outputs.gemini-response != 'No critical or high severity issues found.' && steps.debug_response.outputs.response_status == 'valid'
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GEMINI_RESPONSE: ${{ steps.gemini_review.outputs.gemini-response }}
        with:
          header: gemini-review
          message: |
            ### ✨ AI Review ✨
            
            ${{ env.GEMINI_RESPONSE }}

      - name: Post Fallback Comment
        if: steps.gemini_review.outputs.gemini-response != 'No critical or high severity issues found.' && steps.debug_response.outputs.response_status == 'empty'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gemini-review
          message: |
            ### ⚠️ AI Review - Response Issue ⚠️
            
            The AI reviewer attempted to analyze this PR but the response was empty or malformed. 
            
            Please check the workflow logs for details. This may indicate:
            - Complex markdown content causing YAML parsing issues
            - API response timeout or formatting problems
            - Output variable scoping issues
            
            **Action Required**: Manual code review recommended for this PR.
