name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch history for git diff

      - name: Get PR Diff
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: AI Code Review
        uses: freeedcom/ai-codereviewer@v1
        id: ai_review
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          model: "gemini-1.5-flash"
          review_style: "focused"
          exclude_files: "*.md,*.json"
          custom_prompt: |
            Focus only on critical and high severity issues:
            - Critical: bugs, security vulnerabilities, performance issues
            - High: major design or architectural issues
            Provide file and line context. Be concise and actionable.
            If no issues found, respond: "No critical or high severity issues found."

      - name: Post Review Comment
        if: steps.ai_review.outputs.review-result != 'No critical or high severity issues found.'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ai-review
          message: |
            ### ✨ AI Code Review ✨
            
            ${{ steps.ai_review.outputs.review-result }}
