name: AI PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch history for git diff

      - name: Get PR Diff
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call Gemini API for Review
        id: gemini_review
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an AI code reviewer. Your task is to analyze the provided git diff and identify only the most severe issues.

            **Instructions:**
            1.  **Focus only on `critical` and `high` severity suggestions.** Do not report medium or low-severity issues like style conventions or minor nitpicks.
            2.  **You MUST use one of the following severity levels for your findings:**
                *   `critical`: A potential bug, security vulnerability, or major performance issue.
                *   `high`: A major design or architectural issue.
            3.  **Provide context.** For each suggestion, specify the file and line number if possible.
            4.  **Be concise.** Keep your suggestions and reasoning brief and to the point.
            5.  **If you find no critical or high issues, you MUST respond with the single phrase `No critical or high severity issues found.`**

            ${{ steps.get_diff.outputs.diff }}

      - name: Post Review Comment
        if: steps.gemini_review.outputs.gemini-response != 'No critical or high severity issues found.'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gemini-review
          message: |
            ### ✨ AI Review ✨
            
            ${{ steps.gemini_review.outputs.gemini-response }}
